# Generated by Django 4.2.11 on 2024-05-03 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAPP', '0003_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('test_date', models.DateField()),
                ('test_time', models.TimeField()),
                ('parameter_gen', models.FloatField()),
                ('parameter_bio', models.FloatField()),
                ('parameter_immuno', models.FloatField()),
                ('gen1', models.FloatField(blank=True, null=True)),
                ('bio1', models.FloatField(blank=True, null=True)),
                ('immuno1', models.FloatField(blank=True, null=True)),
                ('distance_svm', models.FloatField(blank=True, null=True)),
                ('indice_knn', models.IntegerField(blank=True, null=True)),
                ('risque', models.CharField(blank=True, max_length=100, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='WEBAPP.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
