# Generated by Django 4.2.11 on 2024-05-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAPP', '0005_lotdetest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotdetest',
            name='admin',
            field=models.EmailField(max_length=254),
        ),
    ]
