# Generated by Django 4.2.11 on 2024-05-12 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAPP', '0006_alter_lotdetest_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotdetest',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
