# Generated by Django 4.2.11 on 2024-05-12 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAPP', '0008_alter_lotdetest_admin_alter_lotdetest_numero_lot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='BKv_peptide_activation',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='test',
            name='background',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='test',
            name='bio_sample_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
