# Generated by Django 4.2.11 on 2024-05-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAPP', '0011_remove_test_parameter_gen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='integer_field',
        ),
        migrations.AddField(
            model_name='test',
            name='power_field',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default='4'),
        ),
        migrations.AlterField(
            model_name='test',
            name='BK_viral_load',
            field=models.IntegerField(default='1'),
        ),
    ]
