# Generated by Django 4.2.13 on 2024-05-26 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAPP', '0012_remove_test_integer_field_test_power_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test_time',
        ),
    ]
